# Generated by Django 4.2.13 on 2024-05-29 13:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_detailblog_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailblog",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "person",
                        wagtail.blocks.StructBlock(
                            [
                                ("firstname", wagtail.blocks.CharBlock()),
                                ("surname", wagtail.blocks.CharBlock()),
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("biography", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    (
                        "detail",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                ("paragraph", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ]
            ),
        ),
    ]
