# Generated by Django 4.2.13 on 2024-06-04 07:28

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("blog", "0005_detailpagetag_detailblog_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailblog",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.DeleteModel(
            name="DetailPageTag",
        ),
    ]
